export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const STUDENT_SIGN_OUT = "STUDENT_SIGN_OUT";


export const MATERIAL_REQUEST = "MATERIAL_REQUEST";
export const MATERIAL_SUCCESS = "MATERIAL_SUCCESS";
export const MATERIAL_FAIL = "MATERIAL_FAIL";

export const MATERIAL_SYLLABUS_REQUEST = "MATERIAL_SYLLABUS_REQUEST";
export const MATERIAL_SYLLABUS_SUCCESS = "MATERIAL_SYLLABUS_SUCCESS";
export const MATERIAL_SYLLABUS_FAIL = "MATERIAL_SYLLABUS_FAIL";


export const CRS_REQUEST = "CRS_REQUEST";
export const CRS_SUCCESS = "CRS_SUCCESS";
export const CRS_FAIL = "CRS_FAIL";

export const MEMBERS_REQUEST = "MEMBERS_REQUEST";
export const MEMBERS_SUCCESS = "MEMBERS_SUCCESS";
export const MEMBERS_FAIL = "MEMBERS_FAIL";

export const PROBLEMS_REQUEST = "PROBLEMS_REQUEST";
export const PROBLEMS_SUCCESS = "PROBLEMS_SUCCESS";
export const PROBLEMS_FAIL = "PROBLEMS_FAIL";

export const MATERIAL_UPLOAD_REQUEST = "MATERIAL_UPLOAD_REQUEST";
export const MATERIAL_UPLOAD_SUCCESS = "MATERIAL_UPLOAD_SUCCESS";
export const MATERIAL_UPLOAD_FAIL = "MATERIAL_UPLOAD_FAIL";


export const SYLLABUS_REQUEST = "SYLLABUS_REQUEST";
export const SYLLABUS_SUCCESS = "SYLLABUS_SUCCESS";
export const SYLLABUS_FAIL = "SYLLABUS_FAIL";


export const SYLLABUS_UPLOAD_REQUEST = "SYLLABUS_UPLOAD_REQUEST";
export const SYLLABUS_UPLOAD_SUCCESS = "SYLLABUS_UPLOAD_SUCCESS";
export const SYLLABUS_UPLOAD_FAIL = "SYLLABUS_UPLOAD_FAIL";

export const VIEW_REQUEST = "VIEW_REQUEST";
export const VIEW_SUCCESS = "VIEW_SUCCESS";
export const VIEW_FAIL = "VIEW_FAIL";

export const MEMBER_ADD_REQUEST = "MEMBER_ADD_REQUEST";
export const MEMBER_ADD_SUCCESS = "MEMBER_ADD_SUCCESS";
export const MEMBER_ADD_FAIL = "MEMBER_ADD_FAIL";

export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAIL = "ADMIN_LIST_FAIL";

export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";

export const PROBLEMS_LIST_REQUEST = "PROBLEMS_LIST_REQUEST";
export const PROBLEMS_LIST_SUCCESS = "PROBLEMS_LIST_SUCCESS";
export const PROBLEMS_LIST_FAIL = "PROBLEMS_LIST_FAIL";
